"""
Django settings for PrestoPantry_project project.

Generated by 'django-admin startproject' using Django 4.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from .base import *

DEBUG = True

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ['PRESTOPANTRY_DB_NAME'],
        'USER': os.environ['PRESTOPANTRY_DB_USER'],
        'PASSWORD': os.environ['PRESTOPANTRY_DB_PASSWORD'],
        'HOST': os.environ['PRESTOPANTRY_DB_HOST'],
        'PORT': os.environ['PRESTOPANTRY_DB_PORT'],

    }
}