# Generated by Django 4.0.2 on 2022-03-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestopantry_app', '0002_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useringredient',
            name='begin_date',
        ),
        migrations.RemoveField(
            model_name='useringredient',
            name='created_record',
        ),
        migrations.RemoveField(
            model_name='useringredient',
            name='current_ind',
        ),
        migrations.RemoveField(
            model_name='useringredient',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='useringredient',
            name='modified_record',
        ),
        migrations.AddField(
            model_name='useringredient',
            name='ingredient_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
