# Generated by Django 4.0.2 on 2022-03-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestopantry_app', '0003_remove_useringredient_begin_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useringredient',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='useringredient',
            name='ingredient_name',
            field=models.CharField(max_length=300),
        ),
    ]
