# Generated by Django 4.0.2 on 2022-04-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestopantry_app', '0004_rename_user_id_useringredient_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useringredient',
            name='upc',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
