# Generated by Django 4.0.2 on 2022-04-02 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestopantry_app', '0003_remove_developer_email_developer_developer_about_and_more'),
        ('prestopantry_app', '0005_useringredient_upc'),
    ]

    operations = [
    ]
