# Generated by Django 4.0.2 on 2022-04-23 02:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prestopantry_app', '0006_merge_20220402_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_api_call',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
