# Generated by Django 4.0.4 on 2022-05-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestopantry_app', '0007_user_last_api_call'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useringredient',
            name='upc',
            field=models.CharField(max_length=50),
        ),
    ]
